/* 🤖 this file was generated by svg-to-ts */
export const tmIconsChat: {
  name: 'chat';
  data: string;
} = {
  name: 'chat',
  data: `<svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M11.2399 29.6873C14.0756 31.3286 17.4114 31.8825 20.6254 31.2458C23.8394 30.6092 26.7122 28.8254 28.7081 26.2271C30.7041 23.6287 31.6869 20.3932 31.4735 17.1237C31.2601 13.8543 29.8649 10.774 27.5481 8.45719C25.2313 6.1404 22.1511 4.74523 18.8816 4.5318C15.6121 4.31837 12.3766 5.30126 9.77826 7.2972C7.17994 9.29314 5.39616 12.1659 4.75951 15.3799C4.12285 18.5939 4.67676 21.9297 6.31798 24.7655L4.55876 30.0178C4.49265 30.216 4.48306 30.4287 4.53105 30.6321C4.57905 30.8355 4.68273 31.0215 4.83048 31.1692C4.97823 31.317 5.16422 31.4206 5.36758 31.4686C5.57095 31.5166 5.78366 31.507 5.98188 31.4409L11.2399 29.6873Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`
};
export const tmIconsDefaultIcon: {
  name: 'default_icon';
  data: string;
} = {
  name: 'default_icon',
  data: `<svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4.59863 10.8169L18.0002 18.1519L31.4018 10.8169" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M18.54 3.51564L30.915 10.2909C31.0917 10.3876 31.2392 10.53 31.3421 10.7031C31.445 10.8763 31.4995 11.0739 31.5 11.2753V24.7247C31.4995 24.9261 31.445 25.1237 31.3421 25.2969C31.2392 25.47 31.0917 25.6124 30.915 25.7091L18.54 32.4844C18.3744 32.575 18.1887 32.6225 18 32.6225C17.8113 32.6225 17.6256 32.575 17.46 32.4844L5.085 25.7091C4.9083 25.6124 4.76079 25.47 4.65789 25.2969C4.55498 25.1237 4.50046 24.9261 4.5 24.7247V11.2753C4.50046 11.0739 4.55498 10.8763 4.65789 10.7031C4.76079 10.53 4.9083 10.3876 5.085 10.2909L17.46 3.51564C17.6256 3.42504 17.8113 3.37756 18 3.37756C18.1887 3.37756 18.3744 3.42504 18.54 3.51564Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M18 18.1533V32.625" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`
};
export type tmIcon = 'chat' | 'default_icon';
export interface TmIcon {
  name: tmIcon;
  data: string;
}
export type TmIconNameSubset<T extends Readonly<TmIcon[]>> = T[number]['name'];
export const completeIconSet = [tmIconsChat, tmIconsDefaultIcon];
