/* 🤖 this file was generated by svg-to-ts */
export const tmIconsArchive: {
  name: 'archive';
  data: string;
} = {
  name: 'archive',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M21 5.25H3C2.58579 5.25 2.25 5.58579 2.25 6V8.25C2.25 8.66421 2.58579 9 3 9H21C21.4142 9 21.75 8.66421 21.75 8.25V6C21.75 5.58579 21.4142 5.25 21 5.25Z" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M20.25 9V18C20.25 18.1989 20.171 18.3897 20.0303 18.5303C19.8897 18.671 19.6989 18.75 19.5 18.75H4.5C4.30109 18.75 4.11032 18.671 3.96967 18.5303C3.82902 18.3897 3.75 18.1989 3.75 18V9" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M9.75 12.75H14.25" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsBellSimpleRinging: {
  name: 'bell_simple_ringing';
  data: string;
} = {
  name: 'bell_simple_ringing',
  data: `<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.5 17.5H12.5" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/><path d="M14.375 1.875C15.5819 2.64509 16.5608 3.72406 17.2102 5" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/><path d="M2.79004 5C3.43939 3.72406 4.41829 2.64509 5.6252 1.875" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/><path d="M4.37515 8.75C4.37515 7.25816 4.96778 5.82742 6.02267 4.77252C7.07756 3.71763 8.5083 3.125 10.0001 3.125C11.492 3.125 12.9227 3.71763 13.9776 4.77252C15.0325 5.82742 15.6251 7.25816 15.6251 8.75C15.6251 11.5484 16.2736 13.1719 16.7892 14.0625C16.844 14.1574 16.8728 14.2649 16.8729 14.3745C16.873 14.484 16.8444 14.5916 16.7898 14.6865C16.7352 14.7815 16.6566 14.8604 16.5619 14.9154C16.4672 14.9705 16.3597 14.9996 16.2501 15H3.75015C3.64076 14.9993 3.53345 14.97 3.43896 14.9149C3.34448 14.8597 3.26611 14.7808 3.2117 14.6859C3.15729 14.591 3.12874 14.4835 3.12891 14.3741C3.12907 14.2647 3.15795 14.1572 3.21265 14.0625C3.72749 13.1719 4.37515 11.5477 4.37515 8.75Z" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsBell: {
  name: 'bell';
  data: string;
} = {
  name: 'bell',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M9 21H15" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M5.24988 9.75C5.24988 7.95979 5.96104 6.2429 7.22691 4.97703C8.49278 3.71116 10.2097 3 11.9999 3C13.7901 3 15.507 3.71116 16.7729 4.97703C18.0387 6.2429 18.7499 7.95979 18.7499 9.75C18.7499 13.1081 19.528 15.8063 20.1468 16.875C20.2125 16.9888 20.2471 17.1179 20.2472 17.2493C20.2474 17.3808 20.2129 17.5099 20.1474 17.6239C20.0819 17.7378 19.9876 17.8325 19.874 17.8985C19.7603 17.9645 19.6313 17.9995 19.4999 18H4.49988C4.36861 17.9992 4.23985 17.964 4.12646 17.8978C4.01308 17.8317 3.91904 17.7369 3.85375 17.6231C3.78845 17.5092 3.7542 17.3801 3.7544 17.2489C3.75459 17.1176 3.78925 16.9887 3.85488 16.875C4.4727 15.8063 5.24988 13.1072 5.24988 9.75Z" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsChat: {
  name: 'chat';
  data: string;
} = {
  name: 'chat',
  data: `<svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M11.2399 29.6873C14.0756 31.3286 17.4114 31.8825 20.6254 31.2458C23.8394 30.6092 26.7122 28.8254 28.7081 26.2271C30.7041 23.6287 31.6869 20.3932 31.4735 17.1237C31.2601 13.8543 29.8649 10.774 27.5481 8.45719C25.2313 6.1404 22.1511 4.74523 18.8816 4.5318C15.6121 4.31837 12.3766 5.30126 9.77826 7.2972C7.17994 9.29314 5.39616 12.1659 4.75951 15.3799C4.12285 18.5939 4.67676 21.9297 6.31798 24.7655L4.55876 30.0178C4.49265 30.216 4.48306 30.4287 4.53105 30.6321C4.57905 30.8355 4.68273 31.0215 4.83048 31.1692C4.97823 31.317 5.16422 31.4206 5.36758 31.4686C5.57095 31.5166 5.78366 31.507 5.98188 31.4409L11.2399 29.6873Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsCheck: {
  name: 'check';
  data: string;
} = {
  name: 'check',
  data: `<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1.875 6.75L4.5 9.375L10.5 3.375" stroke="black" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsDefaultIcon: {
  name: 'default_icon';
  data: string;
} = {
  name: 'default_icon',
  data: `<svg width="36" height="36" viewBox="0 0 36 36" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4.59863 10.8169L18.0002 18.1519L31.4018 10.8169" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M18.54 3.51564L30.915 10.2909C31.0917 10.3876 31.2392 10.53 31.3421 10.7031C31.445 10.8763 31.4995 11.0739 31.5 11.2753V24.7247C31.4995 24.9261 31.445 25.1237 31.3421 25.2969C31.2392 25.47 31.0917 25.6124 30.915 25.7091L18.54 32.4844C18.3744 32.575 18.1887 32.6225 18 32.6225C17.8113 32.6225 17.6256 32.575 17.46 32.4844L5.085 25.7091C4.9083 25.6124 4.76079 25.47 4.65789 25.2969C4.55498 25.1237 4.50046 24.9261 4.5 24.7247V11.2753C4.50046 11.0739 4.55498 10.8763 4.65789 10.7031C4.76079 10.53 4.9083 10.3876 5.085 10.2909L17.46 3.51564C17.6256 3.42504 17.8113 3.37756 18 3.37756C18.1887 3.37756 18.3744 3.42504 18.54 3.51564Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M18 18.1533V32.625" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsDots: {
  name: 'dots';
  data: string;
} = {
  name: 'dots',
  data: `<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10 10.9375C10.5178 10.9375 10.9375 10.5178 10.9375 10C10.9375 9.48223 10.5178 9.0625 10 9.0625C9.48223 9.0625 9.0625 9.48223 9.0625 10C9.0625 10.5178 9.48223 10.9375 10 10.9375Z" fill="black"/><path d="M10 5.625C10.5178 5.625 10.9375 5.20527 10.9375 4.6875C10.9375 4.16973 10.5178 3.75 10 3.75C9.48223 3.75 9.0625 4.16973 9.0625 4.6875C9.0625 5.20527 9.48223 5.625 10 5.625Z" fill="black"/><path d="M10 16.25C10.5178 16.25 10.9375 15.8303 10.9375 15.3125C10.9375 14.7947 10.5178 14.375 10 14.375C9.48223 14.375 9.0625 14.7947 9.0625 15.3125C9.0625 15.8303 9.48223 16.25 10 16.25Z" fill="black"/></svg>`,
};
export const tmIconsFolderOpen: {
  name: 'folder_open';
  data: string;
} = {
  name: 'folder_open',
  data: `<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 26V8C4 7.73478 4.10536 7.48043 4.29289 7.29289C4.48043 7.10536 4.73478 7 5 7H11.6663C11.8826 7 12.0932 7.07018 12.2662 7.2L16 10H25C25.2652 10 25.5196 10.1054 25.7071 10.2929C25.8946 10.4804 26 10.7348 26 11V14" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M4 26L7.7725 14.6838C7.83888 14.4846 7.96623 14.3114 8.13651 14.1887C8.30678 14.066 8.51136 14 8.72125 14H29C29.1585 14 29.3147 14.0376 29.4557 14.1098C29.5968 14.182 29.7186 14.2867 29.8113 14.4153C29.904 14.5438 29.9647 14.6925 29.9886 14.8492C30.0125 15.0058 29.9989 15.1659 29.9487 15.3162L26.3862 26H4Z" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsGear: {
  name: 'gear';
  data: string;
} = {
  name: 'gear',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 15.75C14.0711 15.75 15.75 14.0711 15.75 12C15.75 9.92893 14.0711 8.25 12 8.25C9.92893 8.25 8.25 9.92893 8.25 12C8.25 14.0711 9.92893 15.75 12 15.75Z" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M3.884 16.6959C3.4696 15.9822 3.15212 15.2164 2.93994 14.4188L4.51307 12.45C4.49525 12.149 4.49525 11.8472 4.51307 11.5463L2.94088 9.5775C3.1527 8.77976 3.46953 8.01369 3.88307 7.29938L6.38713 7.01813C6.58709 6.79284 6.80028 6.57965 7.02557 6.37969L7.30682 3.87656C8.0201 3.465 8.78492 3.15005 9.58119 2.94L11.5499 4.51313C11.8509 4.49532 12.1527 4.49532 12.4537 4.51313L14.4224 2.94094C15.2202 3.15276 15.9863 3.46959 16.7006 3.88313L16.9818 6.38719C17.2071 6.58715 17.4203 6.80034 17.6203 7.02563L20.1234 7.30688C20.5378 8.02066 20.8553 8.78645 21.0674 9.58407L19.4943 11.5528C19.5121 11.8538 19.5121 12.1556 19.4943 12.4566L21.0665 14.4253C20.8562 15.2228 20.5409 15.9889 20.129 16.7034L17.6249 16.9847C17.425 17.21 17.2118 17.4232 16.9865 17.6231L16.7053 20.1263C15.9915 20.5407 15.2257 20.8581 14.4281 21.0703L12.4593 19.4972C12.1583 19.515 11.8566 19.515 11.5556 19.4972L9.58682 21.0694C8.78931 20.859 8.02325 20.5438 7.30869 20.1319L7.02744 17.6278C6.80215 17.4279 6.58897 17.2147 6.389 16.9894L3.884 16.6959Z" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsImage: {
  name: 'image';
  data: string;
} = {
  name: 'image',
  data: `<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M16.25 3.125H3.75C3.40482 3.125 3.125 3.40482 3.125 3.75V16.25C3.125 16.5952 3.40482 16.875 3.75 16.875H16.25C16.5952 16.875 16.875 16.5952 16.875 16.25V3.75C16.875 3.40482 16.5952 3.125 16.25 3.125Z" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/><path d="M7.5 8.75C8.19036 8.75 8.75 8.19036 8.75 7.5C8.75 6.80964 8.19036 6.25 7.5 6.25C6.80964 6.25 6.25 6.80964 6.25 7.5C6.25 8.19036 6.80964 8.75 7.5 8.75Z" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/><path d="M4.42871 16.875L12.9951 8.30782C13.0532 8.24971 13.1221 8.20361 13.198 8.17215C13.2738 8.1407 13.3552 8.12451 13.4373 8.12451C13.5194 8.12451 13.6008 8.1407 13.6766 8.17215C13.7525 8.20361 13.8214 8.24971 13.8795 8.30782L16.8748 11.3039" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsLifebuoy: {
  name: 'lifebuoy';
  data: string;
} = {
  name: 'lifebuoy',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 15.75C14.0711 15.75 15.75 14.0711 15.75 12C15.75 9.92893 14.0711 8.25 12 8.25C9.92893 8.25 8.25 9.92893 8.25 12C8.25 14.0711 9.92893 15.75 12 15.75Z" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M9.34873 9.34873L5.63623 5.63623" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M14.6514 9.34873L18.3639 5.63623" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M14.6514 14.6512L18.3639 18.3637" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M9.34873 14.6512L5.63623 18.3637" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsMagnifyingGlass: {
  name: 'magnifying_glass';
  data: string;
} = {
  name: 'magnifying_glass',
  data: `<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M14 24C19.5228 24 24 19.5228 24 14C24 8.47715 19.5228 4 14 4C8.47715 4 4 8.47715 4 14C4 19.5228 8.47715 24 14 24Z" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M21.0713 21.0712L28 28" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsNote: {
  name: 'note';
  data: string;
} = {
  name: 'note',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M14.6897 20.25H4.5C4.30109 20.25 4.11032 20.171 3.96967 20.0303C3.82902 19.8897 3.75 19.6989 3.75 19.5V4.5C3.75 4.30109 3.82902 4.11032 3.96967 3.96967C4.11032 3.82902 4.30109 3.75 4.5 3.75H19.5C19.6989 3.75 19.8897 3.82902 20.0303 3.96967C20.171 4.11032 20.25 4.30109 20.25 4.5V14.6897C20.2499 14.8883 20.171 15.0788 20.0306 15.2194L15.2194 20.0306C15.0788 20.171 14.8883 20.2499 14.6897 20.25Z" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M20.1825 14.9991H15V20.1816" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsPalette: {
  name: 'palette';
  data: string;
} = {
  name: 'palette',
  data: `<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10 15C10 14.5027 10.1975 14.0258 10.5492 13.6742C10.9008 13.3226 11.3777 13.125 11.875 13.125H15.4852C15.9098 13.1251 16.322 12.981 16.6541 12.7163C16.9862 12.4516 17.2186 12.082 17.3133 11.668C17.4423 11.0995 17.505 10.5181 17.5 9.93517C17.4648 5.80861 14.05 2.45861 9.92188 2.50001C7.94632 2.52059 6.05868 3.31985 4.66901 4.72414C3.27934 6.12844 2.49989 8.02435 2.5 10C2.5 13.2664 4.58828 15.7375 7.5 16.7664C7.7827 16.8664 8.08525 16.8971 8.38226 16.8559C8.67927 16.8148 8.96209 16.703 9.20698 16.53C9.45186 16.3569 9.65168 16.1277 9.78967 15.8615C9.92766 15.5953 9.99978 15.2999 10 15Z" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/><path d="M10 6.875C10.5178 6.875 10.9375 6.45527 10.9375 5.9375C10.9375 5.41973 10.5178 5 10 5C9.48223 5 9.0625 5.41973 9.0625 5.9375C9.0625 6.45527 9.48223 6.875 10 6.875Z" fill="black"/><path d="M6.5625 8.75C7.08027 8.75 7.5 8.33027 7.5 7.8125C7.5 7.29473 7.08027 6.875 6.5625 6.875C6.04473 6.875 5.625 7.29473 5.625 7.8125C5.625 8.33027 6.04473 8.75 6.5625 8.75Z" fill="black"/><path d="M6.5625 13.125C7.08027 13.125 7.5 12.7053 7.5 12.1875C7.5 11.6697 7.08027 11.25 6.5625 11.25C6.04473 11.25 5.625 11.6697 5.625 12.1875C5.625 12.7053 6.04473 13.125 6.5625 13.125Z" fill="black"/><path d="M13.4375 8.75C13.9553 8.75 14.375 8.33027 14.375 7.8125C14.375 7.29473 13.9553 6.875 13.4375 6.875C12.9197 6.875 12.5 7.29473 12.5 7.8125C12.5 8.33027 12.9197 8.75 13.4375 8.75Z" fill="black"/></svg>`,
};
export const tmIconsPlus: {
  name: 'plus';
  data: string;
} = {
  name: 'plus',
  data: `<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3.125 10H16.875" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/><path d="M10 3.125V16.875" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsPushPin: {
  name: 'push_pin';
  data: string;
} = {
  name: 'push_pin',
  data: `<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17.9422 7.68279C18.0594 7.56559 18.1252 7.40668 18.1252 7.24099C18.1252 7.0753 18.0594 6.9164 17.9422 6.7992L13.2032 2.05779C13.086 1.94067 12.9271 1.87488 12.7614 1.87488C12.5957 1.87488 12.4368 1.94067 12.3196 2.05779L7.84303 6.54685C7.84303 6.54685 5.67506 5.46326 3.35943 7.33201C3.29077 7.38697 3.23447 7.45581 3.19424 7.53402C3.154 7.61224 3.13072 7.69806 3.12593 7.78589C3.12114 7.87371 3.13493 7.96156 3.16642 8.04369C3.19791 8.12581 3.24637 8.20037 3.30865 8.26248L11.7383 16.6914C11.8015 16.7541 11.8773 16.8025 11.9606 16.8336C12.044 16.8646 12.133 16.8775 12.2218 16.8713C12.3105 16.8652 12.3969 16.8402 12.4752 16.798C12.5535 16.7558 12.6219 16.6973 12.6758 16.6265C13.3313 15.7547 14.361 13.9633 13.4657 12.1734L17.9422 7.68279Z" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/><path d="M7.52266 12.4774L3.75 16.25" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsSignOut: {
  name: 'sign_out';
  data: string;
} = {
  name: 'sign_out',
  data: `<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8.75 3.125H3.75V16.875H8.75" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/><path d="M8.75 10H17.5" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/><path d="M14.375 6.875L17.5 10L14.375 13.125" stroke="black" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const tmIconsTrash: {
  name: 'trash';
  data: string;
} = {
  name: 'trash',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20.25 5.25H3.75" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M9.75 9.75V15.75" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M14.25 9.75V15.75" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M18.75 5.25V19.5C18.75 19.6989 18.671 19.8897 18.5303 20.0303C18.3897 20.171 18.1989 20.25 18 20.25H6C5.80109 20.25 5.61032 20.171 5.46967 20.0303C5.32902 19.8897 5.25 19.6989 5.25 19.5V5.25" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M15.75 5.25V3.75C15.75 3.35218 15.592 2.97064 15.3107 2.68934C15.0294 2.40804 14.6478 2.25 14.25 2.25H9.75C9.35218 2.25 8.97064 2.40804 8.68934 2.68934C8.40804 2.97064 8.25 3.35218 8.25 3.75V5.25" stroke="black" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export type tmIcon =
  | 'archive'
  | 'bell_simple_ringing'
  | 'bell'
  | 'chat'
  | 'check'
  | 'default_icon'
  | 'dots'
  | 'folder_open'
  | 'gear'
  | 'image'
  | 'lifebuoy'
  | 'magnifying_glass'
  | 'note'
  | 'palette'
  | 'plus'
  | 'push_pin'
  | 'sign_out'
  | 'trash';
export interface TmIcon {
  name: tmIcon;
  data: string;
}
export type TmIconNameSubset<T extends Readonly<TmIcon[]>> = T[number]['name'];
export const completeIconSet = [
  tmIconsArchive,
  tmIconsBellSimpleRinging,
  tmIconsBell,
  tmIconsChat,
  tmIconsCheck,
  tmIconsDefaultIcon,
  tmIconsDots,
  tmIconsFolderOpen,
  tmIconsGear,
  tmIconsImage,
  tmIconsLifebuoy,
  tmIconsMagnifyingGlass,
  tmIconsNote,
  tmIconsPalette,
  tmIconsPlus,
  tmIconsPushPin,
  tmIconsSignOut,
  tmIconsTrash,
];
