name: Deploy to Vercel

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Install start-server-and-test
        run: npm install --save-dev start-server-and-test

      - name: Run Cypress tests
        run: npm run cypress:ci
        env:
            CYPRESS_TEST_USER_LOGIN: ${{ secrets.CYPRESS_TEST_USER_LOGIN }}
            CYPRESS_TEST_USER_PASSWORD: ${{ secrets.CYPRESS_TEST_USER_PASSWORD }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod --yes'
          working-directory: ./
